export const EVENT_PROFILE_UPDATED = "PROFILE_UPDATED";
export const EVENT_USER_LANGUAGE_ADDED = "USER_LANGUAGE_ADDED";
export const EVENT_USER_LANGUAGE_REMOVED = "USER_LANGUAGE_REMOVED";
export const EVENT_ACTIVE_LANGUAGE_CHANGED = "ACTIVE_LANGUAGE_CHANGED";