export const PREDEFINED_LANGUAGES = [
    { code: "en", name: "English" },
    { code: "fr", name: "Français" },
    { code: "es", name: "Español" },
    { code: "de", name: "Deutsch" },
    { code: "it", name: "Italiano" },
    { code: "pt", name: "Português" },
    { code: "ru", name: "Русский" },
    { code: "zh", name: "中文" },
    { code: "ja", name: "日本語" },
    { code: "ar", name: "العربية" },
    { code: "hi", name: "हिन्दी" },
    { code: "ko", name: "한국어" },
    { code: "vi", name: "Tiếng Việt" },
    { code: "tr", name: "Türkçe" },
    { code: "fa", name: "فارسی" }
];

export const LANGUAGE_TO_COUNTRY_MAPPING: Record<string, string> = {
    "en": "gb",
    "fr": "fr",
    "es": "es",
    "de": "de",
    "it": "it",
    "pt": "pt",
    "ru": "ru",
    "zh": "cn",
    "ja": "jp",
    "ar": "dz",
    "hi": "in",
    "ko": "kr",
    "vi": "vn",
    "tr": "tr",
    "fa": "ir",
};